[package]
name = "paracord-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[features]
default = ["native-media", "backup"]
native-media = ["dep:paracord-relay", "dep:paracord-transport"]
backup = ["dep:rusqlite", "dep:flate2", "dep:tar", "dep:tempfile"]

[dependencies]
paracord-models = { workspace = true }
paracord-db = { workspace = true }
paracord-util = { workspace = true }
paracord-media = { workspace = true }
paracord-federation = { workspace = true }
paracord-relay = { workspace = true, optional = true }
paracord-transport = { workspace = true, optional = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
moka = { workspace = true }
regex = { workspace = true }
unicode-normalization = { workspace = true }
unicode-properties = { workspace = true }
dashmap = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled"], optional = true }
flate2 = { version = "1", optional = true }
tar = { version = "0.4", optional = true }
tempfile = { workspace = true, optional = true }
